name: bounce-bench
version: 0.1.0
category: acme

dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - sdl2
  - mtl
  - text
  - array
  - lens
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat
  - clock
  - monad-loops


ghc-options:
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

default-extensions:
  - NoImplicitPrelude
  - DataKinds
  - TypeFamilies
  - FlexibleContexts
  - TemplateHaskell
  - DeriveGeneric
  - DeriveAnyClass
  - NoStarIsType
  - TypeOperators
  - TypeApplications
  - ScopedTypeVariables

source-dirs:
  - src
  
executables:
  sim-batch:
    source-dirs: sim
    main: sim-batch.hs

  sim-sdl:
    source-dirs: sim
    main: sim-sdl.hs

  sim-ffi:
    source-dirs:
      - sim
      - csim
    main: sim-ffi.hs

    build-tools: hsc2hs
    c-sources:
        - csim/Bounce.h
        - csim/Bounce.c
    include-dirs: csim
