name: bounce-bench
version: 0.1.0
category: acme

dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - retroclash-lib
  - retroclash-sim

  - sdl2
  - mtl
  - transformers
  - text
  - array
  - lens
  - clock
  - monad-loops

ghc-options:
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver
  -O3

default-extensions:
  - NoImplicitPrelude
  - DataKinds
  - TypeFamilies
  - FlexibleContexts
  - TemplateHaskell
  - DeriveGeneric
  - DeriveAnyClass
  - NoStarIsType
  - TypeOperators
  - TypeApplications
  - ScopedTypeVariables

source-dirs:
  - src
  
executables:
  sim-hs:
    source-dirs: sim
    main: sim-hs.hs

  sim-hs-sdl:
    source-dirs: sim
    main: sim-hs-sdl.hs

  sim-ffi: &ffi
    source-dirs:
      - sim
      - csim
    main: sim-ffi.hs

    build-tools: hsc2hs
    include-dirs: csim
    c-sources:
        - csim/Bounce.c
    cc-options: -O3
    
  sim-ffi-sdl:
    <<: *ffi
    main: sim-ffi-sdl.hs

  sim-verilator: &verilator
    source-dirs:
      - sim
      - verilator
    main: sim-verilator.hs
    extra-libraries: stdc++ 
    extra-lib-dirs: verilator
    ghc-options:
        -fPIC
        -pgml g++
        -optl-Wl,--allow-multiple-definition -optl-Wl,--whole-archive
        -optl-Wl,-Bstatic -optl-Wl,-L_build/verilator -optl-Wl,-lVerilatorFFI -optl-Wl,-Bdynamic
        -optl-Wl,--no-whole-archive
    
    build-tools: hsc2hs
    include-dirs: verilator

  sim-verilator-sdl:
    <<: *verilator
    main: sim-verilator-sdl.hs
